#!/usr/bin/env bash
set -euo pipefail

# Competition profile confirmed on 2026-09-06:
# - paper_ball secondary route uses generation 7 ONNX only
# - secondary accept threshold is 0.12
# - RGB-D vote is disabled so enhanced detections use the tracked secondary stream
# - paper/box stable supplement is disabled in this release profile
# - no navigation goal is published from this script

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASE_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

G7_MODEL="$RELEASE_ROOT/models/paper_ball_robotview_continue7_20260906_150818_best.onnx"

PRIMARY_MODEL_FALLBACK="/home/hyc/robocup_vision/yolov8s-worldv2-garbage.onnx"

if [[ ! -f "$G7_MODEL" ]]; then
  echo "ERROR: generation 7 paper_ball model not found: $G7_MODEL" >&2
  exit 1
fi

export PRIMARY_MODEL_PATH="${PRIMARY_MODEL_PATH:-$PRIMARY_MODEL_FALLBACK}"
export PAPER_BOX_SECONDARY_MODEL_PATH="${PAPER_BOX_SECONDARY_MODEL_PATH:-$G7_MODEL}"
export ENABLE_PAPER_BOX_SUPPLEMENT="${ENABLE_PAPER_BOX_SUPPLEMENT:-false}"
export ENABLE_PAPER_BOX_SECONDARY="${ENABLE_PAPER_BOX_SECONDARY:-true}"

export CAMERA_SOURCE="${CAMERA_SOURCE:-kinect2}"
export CAMERA_IMAGE_TOPIC="${CAMERA_IMAGE_TOPIC:-/kinect2/hd/image_color}"
export YOLO_EXECUTION_PROVIDER="${YOLO_EXECUTION_PROVIDER:-cpu}"

export PRIMARY_CONFIDENCE_THRESHOLD="${PRIMARY_CONFIDENCE_THRESHOLD:-0.18}"
export PAPER_BOX_DETECTOR_CONFIDENCE_THRESHOLD="${PAPER_BOX_DETECTOR_CONFIDENCE_THRESHOLD:-0.12}"
export PAPER_BOX_CONFIDENCE_THRESHOLD="${PAPER_BOX_CONFIDENCE_THRESHOLD:-0.30}"

export PAPER_BOX_SECONDARY_DETECTOR_CONFIDENCE_THRESHOLD="${PAPER_BOX_SECONDARY_DETECTOR_CONFIDENCE_THRESHOLD:-0.06}"
export PAPER_BOX_SECONDARY_CONFIDENCE_THRESHOLD="${PAPER_BOX_SECONDARY_CONFIDENCE_THRESHOLD:-0.12}"
export BYTETRACK_LOW_CONFIDENCE_THRESHOLD="${BYTETRACK_LOW_CONFIDENCE_THRESHOLD:-0.06}"
export PAPER_BOX_SECONDARY_BYTETRACK_MIN_TRACK_HITS="${PAPER_BOX_SECONDARY_BYTETRACK_MIN_TRACK_HITS:-1}"
export PAPER_BOX_SECONDARY_TEMPORAL_HOLD_MINIMUM_COUNT="${PAPER_BOX_SECONDARY_TEMPORAL_HOLD_MINIMUM_COUNT:-0}"
export PAPER_BOX_SECONDARY_TEMPORAL_HOLD_SECONDS="${PAPER_BOX_SECONDARY_TEMPORAL_HOLD_SECONDS:-0.0}"
export PAPER_BOX_SECONDARY_FALLBACK_CENTER_CROP_SCALE="${PAPER_BOX_SECONDARY_FALLBACK_CENTER_CROP_SCALE:-1.8}"
export PAPER_BOX_SECONDARY_FALLBACK_CROP_MODE="${PAPER_BOX_SECONDARY_FALLBACK_CROP_MODE:-center_bottom}"

export ENABLE_PAPER_BALL_RGBD_VOTE="${ENABLE_PAPER_BALL_RGBD_VOTE:-false}"
export PAPER_BALL_RGBD_VOTE_POINT_CLOUD_TOPIC="${PAPER_BALL_RGBD_VOTE_POINT_CLOUD_TOPIC:-/kinect2/hd/points}"
export PAPER_BALL_RGBD_VOTE_OUTPUT_FRAME="${PAPER_BALL_RGBD_VOTE_OUTPUT_FRAME:-base_link}"

exec "$SCRIPT_DIR/start_robocup_garbage_realtime.sh" "$@"
